project:
  type: book
  output-dir: docs

book:
  title: "Phil's remote sensing learning diary"
  author: "Philyoung Jeong"
  date: "2023. 1. 24."
  chapters:
    - index.qmd
    - week_1.qmd
    - week_2.qmd
    - week_3.qmd
    - week_4.qmd
    - weej_5.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

